# Generated by Django 4.2.3 on 2023-07-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_post_likes",
                to="post.post",
            ),
        ),
    ]
